# YOLOv8n + ByteTrack Configuration
pipeline: 
  detector:
    model: yolov8n
    categories: ['Air Craft Carrier', 'Bulk-Carrier', 'Container Ship', 'Cruise Ship', 'Drilling Ship', 'LNG', 'Naval', 'Offshore Platform', 'Ro-Ro', 'Tanker', 'Tug-Boat', 'Yacht']
    thresholds:
      confidence: 0.6
      iou: 0.4
    slicing:
      overlap: 0.2
    device: cuda:0

  tracker:
    algorithm: bytetrack
